DELETE FROM ANSWER;
DELETE FROM QUESTION;
DELETE FROM QUIZ;

INSERT INTO QUESTION (QUESTION_CONTENT, DIFFICULTY, LIBRARY_ID)
VALUES ('What is the capital of Canada?', 1, 1);
	
	
	INSERT INTO ANSWERS (ANSWER_CONTENT, IS_CORRECT, id)
	VALUES ('Ottawa', true, SELECT QUESTION_ID FROM QUESTION WHERE QUESTION_CONTENT = 'What is the capital of Canada?');
